version: '3.8'

services:
  authen-app:
    build: .
    image: authen-app:1.0.0
    container_name: authen-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
